//! `user.linuxqq_cache` + `user.linuxqq_media` — LinuxQQ cleanup.
//!
//! ## Audit summary
//!
//! Tencent's LinuxQQ stores its data under `~/.config/QQ/` and physically
//! separates the chat *text* from the chat *media*:
//!
//! * **`nt_qq_<account-hash>/nt_db/*.db`** — SQLite databases holding every
//!   message (`nt_msg.db`), full-text-search indexes, group metadata,
//!   profiles. **This is the chat history. Both cleaners refuse to touch
//!   this directory under any circumstances.**
//!
//! * **`nt_qq_<account-hash>/nt_data/{Pic,Video,Ptt,File,...}`** — cached
//!   media that was sent or received in chats. Deleting these does not
//!   remove the message records, but the QQ client will show "image
//!   expired" / "file expired" for items the Tencent server no longer
//!   retains. This is the dangerous bucket.
//!
//! * **Top-level Electron caches** (`Cache/`, `Code Cache/`, `GPUCache/`),
//!   per-account logs (`nt_data/log/`, `nt_data/log-cache/`), download
//!   partials (`Pic/<YYYY-MM>/{Ori,Thumb}Temp/`), hot-loaded code
//!   (`dynamic_module/`, `dynamic_package/`, `arks/`) and global emoji /
//!   search caches are all regenerable. This is the safe bucket.
//!
//! Login state (top-level `Cookies`, `Preferences`, `Local Storage/`,
//! `Partitions/`, `Trust Tokens`, `global/nt_db/login.db`) and per-account
//! KV state (`mmkv/`, `msf/`, `UnitedConfig/`, …) are never touched —
//! removing them would log the user out and lose preferences.

use std::path::{Path, PathBuf};

use camino::Utf8PathBuf;
use wisp_core::types::{CleanAction, CleanerGroup, CleanerId, CleanerMeta, DeletionVia, RiskLevel};
use wisp_platform::Distro;

use crate::{CLEANERS, CleanCtx, CleanerEntry, PlanFuture};

// ─── Path registries ──────────────────────────────────────────────────────────

/// Root, relative to `$HOME`.
const QQ_ROOT_REL: &str = ".config/QQ";

/// Per-account directory prefix. The full name is e.g.
/// `nt_qq_ad8d0cca79bed24ae8dea40bd8ff5dd7`.
const ACCOUNT_PREFIX: &str = "nt_qq_";

/// Top-level Electron-shell caches and ephemeral logs. All regenerated by
/// QQ on next launch, none contain user-meaningful state.
const TOPLEVEL_CACHE_DIRS: &[&str] = &[
    "Cache",
    "Code Cache",
    "GPUCache",
    "Shared Dictionary",
    "Crashpad",
    "log",
    "logs",
    "crash_files",
    "arks",
    "dynamic_module",
    "dynamic_package",
];

/// Caches under `~/.config/QQ/global/`. Login state under `global/nt_db`
/// and `global/nt_data/{Login,mmkv,msf,...}` is intentionally absent.
const GLOBAL_CACHE_DIRS: &[&str] = &["global/nt_data/Log", "global/nt_data/search"];

/// Per-account safe-cache subdirectories (relative to each `nt_qq_<hash>/`).
const PER_ACCOUNT_CACHE_DIRS: &[&str] = &["nt_data/log", "nt_data/log-cache", "nt_temp"];

/// Per-account media subdirectories. Deletion is recoverable from trash but
/// the server may not have the originals any more, so this lives behind the
/// `linuxqq_media` (Dangerous) cleaner.
const PER_ACCOUNT_MEDIA_DIRS: &[&str] = &[
    "nt_data/Pic",
    "nt_data/Video",
    "nt_data/Ptt",
    "nt_data/File",
    "nt_data/Emoji",
    "nt_data/avatar",
];

/// Global media caches (shared across accounts).
const GLOBAL_MEDIA_DIRS: &[&str] = &["global/nt_data/Emoji"];

// ─── Enumeration helpers ──────────────────────────────────────────────────────

/// Return every per-account directory under `qq_root` (entries whose name
/// starts with `nt_qq_`). LinuxQQ supports multi-account, so a user can
/// have several of these side by side.
fn linuxqq_accounts(qq_root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let Ok(rd) = std::fs::read_dir(qq_root) else {
        return out;
    };
    for entry in rd.flatten() {
        let Ok(ft) = entry.file_type() else { continue };
        if !ft.is_dir() {
            continue;
        }
        let name = entry.file_name();
        if name.to_string_lossy().starts_with(ACCOUNT_PREFIX) {
            out.push(entry.path());
        }
    }
    out
}

/// Enumerate every `<account>/nt_data/Pic/<YYYY-MM>/{OriTemp,ThumbTemp}/`
/// directory. These are download partials — empty most of the time but
/// can hold orphaned bytes, and they're the only safe-to-delete subset of
/// the per-month picture trees (`Ori/` and `Thumb/` are media, not cache).
fn pic_temp_dirs(account_root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let pic_root = account_root.join("nt_data").join("Pic");
    let Ok(rd) = std::fs::read_dir(&pic_root) else {
        return out;
    };
    for entry in rd.flatten() {
        let Ok(ft) = entry.file_type() else { continue };
        if !ft.is_dir() {
            continue;
        }
        let month = entry.path();
        for sub in &["OriTemp", "ThumbTemp"] {
            let candidate = month.join(sub);
            if candidate.exists() {
                out.push(candidate);
            }
        }
    }
    out
}

// ─── Action builders ──────────────────────────────────────────────────────────

fn push_delete(actions: &mut Vec<CleanAction>, path: PathBuf, via: DeletionVia) {
    if !path.exists() {
        return;
    }
    let size = wisp_core::trash::path_size(&path);
    if let Ok(utf8) = Utf8PathBuf::from_path_buf(path) {
        actions.push(CleanAction::Delete {
            path: utf8,
            size,
            via,
        });
    }
}

fn collect_cache_actions(qq_root: &Path) -> Vec<CleanAction> {
    let mut actions = Vec::new();

    for rel in TOPLEVEL_CACHE_DIRS {
        push_delete(&mut actions, qq_root.join(rel), DeletionVia::Direct);
    }
    for rel in GLOBAL_CACHE_DIRS {
        push_delete(&mut actions, qq_root.join(rel), DeletionVia::Direct);
    }
    for account in linuxqq_accounts(qq_root) {
        for rel in PER_ACCOUNT_CACHE_DIRS {
            push_delete(&mut actions, account.join(rel), DeletionVia::Direct);
        }
        for temp in pic_temp_dirs(&account) {
            push_delete(&mut actions, temp, DeletionVia::Direct);
        }
    }

    actions
}

fn collect_media_actions(qq_root: &Path) -> Vec<CleanAction> {
    let mut actions = Vec::new();

    for rel in GLOBAL_MEDIA_DIRS {
        push_delete(&mut actions, qq_root.join(rel), DeletionVia::Trash);
    }
    for account in linuxqq_accounts(qq_root) {
        for rel in PER_ACCOUNT_MEDIA_DIRS {
            push_delete(&mut actions, account.join(rel), DeletionVia::Trash);
        }
    }

    actions
}

// ─── Cleaner: user.linuxqq_cache ──────────────────────────────────────────────

struct LinuxQQCacheMeta;

impl CleanerMeta for LinuxQQCacheMeta {
    fn id(&self) -> CleanerId {
        CleanerId::new("user.linuxqq_cache")
    }
    fn name(&self) -> &str {
        "LinuxQQ caches"
    }
    fn description(&self) -> &str {
        "Electron shell caches, app logs, hot-loaded code packages, search / emoji-index caches \
         and download partials for Tencent QQ. Does NOT touch chat history (nt_db/) or any media \
         received in chats. Safe to run while QQ is closed."
    }
    fn risk(&self) -> RiskLevel {
        RiskLevel::Safe
    }
    fn requires_root(&self) -> bool {
        false
    }
    fn supported_on(&self, _distro: &dyn Distro) -> bool {
        true
    }
    fn group(&self) -> CleanerGroup {
        CleanerGroup::User
    }
}

fn plan_cache<'a>(_ctx: &'a CleanCtx) -> PlanFuture<'a> {
    Box::pin(async move {
        let Some(home) = crate::home_dir() else {
            return Ok(Vec::new());
        };
        let qq_root = home.join(QQ_ROOT_REL);
        if !qq_root.exists() {
            return Ok(Vec::new());
        }
        Ok(collect_cache_actions(&qq_root))
    })
}

static META_CACHE: LinuxQQCacheMeta = LinuxQQCacheMeta;

#[linkme::distributed_slice(CLEANERS)]
static ENTRY_CACHE: CleanerEntry = CleanerEntry {
    meta: &META_CACHE,
    plan: plan_cache,
};

// ─── Cleaner: user.linuxqq_media ──────────────────────────────────────────────

struct LinuxQQMediaMeta;

impl CleanerMeta for LinuxQQMediaMeta {
    fn id(&self) -> CleanerId {
        CleanerId::new("user.linuxqq_media")
    }
    fn name(&self) -> &str {
        "LinuxQQ chat media"
    }
    fn description(&self) -> &str {
        "Cached pictures, videos, voice messages, files, emoji packs and avatars from Tencent QQ \
         chats. Does NOT delete chat text history (nt_db/), but old messages may show \
         'image expired' / 'file expired' for items the Tencent server no longer retains. \
         Files are sent to the trash for recoverability."
    }
    fn risk(&self) -> RiskLevel {
        RiskLevel::Dangerous
    }
    fn requires_root(&self) -> bool {
        false
    }
    fn supported_on(&self, _distro: &dyn Distro) -> bool {
        true
    }
    fn group(&self) -> CleanerGroup {
        CleanerGroup::User
    }
}

fn plan_media<'a>(_ctx: &'a CleanCtx) -> PlanFuture<'a> {
    Box::pin(async move {
        let Some(home) = crate::home_dir() else {
            return Ok(Vec::new());
        };
        let qq_root = home.join(QQ_ROOT_REL);
        if !qq_root.exists() {
            return Ok(Vec::new());
        }
        Ok(collect_media_actions(&qq_root))
    })
}

static META_MEDIA: LinuxQQMediaMeta = LinuxQQMediaMeta;

#[linkme::distributed_slice(CLEANERS)]
static ENTRY_MEDIA: CleanerEntry = CleanerEntry {
    meta: &META_MEDIA,
    plan: plan_media,
};

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    /// Build a faithful subset of a real LinuxQQ tree under `root`, including:
    ///
    /// * Two accounts (multi-account check)
    /// * Top-level Electron caches + login state
    /// * Per-account `nt_db/*.db` (the chat history we must not touch)
    /// * Per-account `nt_data/{Pic,Video,Ptt,File,Emoji,avatar,log,...}`
    ///   plus the `mmkv/msf/UnitedConfig` KV state we must not touch
    /// * Per-month Pic subdirs with `Ori`, `Thumb`, `OriTemp`, `ThumbTemp`
    /// * `global/{nt_data,nt_db}` with the same shape
    fn build_qq_tree(root: &Path) {
        // Top-level caches
        for d in TOPLEVEL_CACHE_DIRS {
            fs::create_dir_all(root.join(d)).unwrap();
            fs::write(root.join(d).join("blob"), b"x").unwrap();
        }
        // Top-level login state — NEVER TOUCH
        fs::write(root.join("Cookies"), b"cookies").unwrap();
        fs::write(root.join("Preferences"), b"prefs").unwrap();
        fs::create_dir_all(root.join("Local Storage")).unwrap();
        fs::write(root.join("Local Storage/leveldb.ldb"), b"x").unwrap();
        fs::create_dir_all(root.join("Partitions/site_a")).unwrap();
        fs::write(root.join("Partitions/site_a/x"), b"x").unwrap();

        // Global tree
        fs::create_dir_all(root.join("global/nt_data/Log")).unwrap();
        fs::write(root.join("global/nt_data/Log/q.log"), b"log").unwrap();
        fs::create_dir_all(root.join("global/nt_data/search")).unwrap();
        fs::write(root.join("global/nt_data/search/idx"), b"idx").unwrap();
        fs::create_dir_all(root.join("global/nt_data/Emoji")).unwrap();
        fs::write(root.join("global/nt_data/Emoji/sticker.png"), b"png").unwrap();
        // Login state — NEVER TOUCH
        fs::create_dir_all(root.join("global/nt_db")).unwrap();
        fs::write(root.join("global/nt_db/login.db"), b"login").unwrap();
        fs::create_dir_all(root.join("global/nt_data/Login")).unwrap();
        fs::write(root.join("global/nt_data/Login/state"), b"x").unwrap();

        // Two accounts
        for account in &["nt_qq_aaaaaaaaaaaaaaaa", "nt_qq_bbbbbbbbbbbbbbbb"] {
            let acc = root.join(account);
            // Chat history — NEVER TOUCH
            fs::create_dir_all(acc.join("nt_db")).unwrap();
            fs::write(acc.join("nt_db/nt_msg.db"), b"messages").unwrap();
            fs::write(acc.join("nt_db/group_msg_fts.db"), b"fts").unwrap();
            fs::write(acc.join("nt_db/buddy_msg_fts.db"), b"fts").unwrap();
            // Per-account safe caches
            fs::create_dir_all(acc.join("nt_data/log")).unwrap();
            fs::write(acc.join("nt_data/log/q.log"), b"log").unwrap();
            fs::create_dir_all(acc.join("nt_data/log-cache")).unwrap();
            fs::write(acc.join("nt_data/log-cache/cache.mmap3"), b"x").unwrap();
            fs::create_dir_all(acc.join("nt_temp/session")).unwrap();
            fs::write(acc.join("nt_temp/session/x"), b"x").unwrap();
            // Per-account media
            for media in &["Video", "Ptt", "File", "Emoji", "avatar"] {
                fs::create_dir_all(acc.join("nt_data").join(media)).unwrap();
                fs::write(acc.join("nt_data").join(media).join("blob.bin"), b"media").unwrap();
            }
            // Per-month Pic structure
            for month in &["2024-06", "2025-01"] {
                let m = acc.join("nt_data/Pic").join(month);
                for sub in &["Ori", "Thumb", "OriTemp", "ThumbTemp"] {
                    fs::create_dir_all(m.join(sub)).unwrap();
                }
                fs::write(m.join("Ori/img.jpg"), b"original").unwrap();
                fs::write(m.join("Thumb/img.jpg"), b"thumb").unwrap();
                fs::write(m.join("OriTemp/.partial"), b"part").unwrap();
                // Leave ThumbTemp empty
            }
            // KV state — NEVER TOUCH
            for kv in &[
                "ams",
                "mmkv",
                "msf",
                "UnitedConfig",
                "PrivilegeIcon",
                "OnlineStatus",
                "Qzone",
                "flashfransfer",
                "dataline",
            ] {
                fs::create_dir_all(acc.join("nt_data").join(kv)).unwrap();
                fs::write(acc.join("nt_data").join(kv).join("state"), b"x").unwrap();
            }
        }

        // A non-account directory at top level — must NOT be picked up.
        fs::create_dir_all(root.join("qqgame")).unwrap();
    }

    fn collect_paths(actions: &[CleanAction]) -> Vec<String> {
        actions
            .iter()
            .map(|a| match a {
                CleanAction::Delete { path, .. } => path.as_str().to_owned(),
                _ => panic!("expected Delete action"),
            })
            .collect()
    }

    /// Assert that no action's path contains any of the forbidden tokens.
    /// This is the load-bearing safety check: chat-history files
    /// (`nt_db/*.db`), login state (`Cookies`, `Preferences`, `Partitions`,
    /// `Local Storage`, `global/nt_db`) and per-account KV state (`mmkv`,
    /// `msf`, `UnitedConfig`, etc.) must never appear as a deletion target.
    fn assert_forbidden_absent(paths: &[String]) {
        let forbidden = [
            "nt_db",
            "Cookies",
            "Preferences",
            "Partitions",
            "Local Storage",
            "/mmkv",
            "/msf",
            "/UnitedConfig",
            "/PrivilegeIcon",
            "/OnlineStatus",
            "/Qzone",
            "/flashfransfer",
            "/dataline",
            "/ams",
            "global/nt_data/Login",
        ];
        for path in paths {
            for token in &forbidden {
                assert!(
                    !path.contains(token),
                    "forbidden token {token:?} found in action path {path:?}"
                );
            }
        }
    }

    #[test]
    fn linuxqq_accounts_picks_up_nt_qq_prefix_only() {
        let tmp = TempDir::new().unwrap();
        let root = tmp.path();
        fs::create_dir_all(root.join("nt_qq_aaaaaaaa")).unwrap();
        fs::create_dir_all(root.join("nt_qq_bbbbbbbb")).unwrap();
        fs::create_dir_all(root.join("qqgame")).unwrap();
        fs::create_dir_all(root.join("global")).unwrap();
        fs::write(root.join("Cookies"), b"x").unwrap();

        let mut accounts = linuxqq_accounts(root)
            .into_iter()
            .map(|p| p.file_name().unwrap().to_string_lossy().into_owned())
            .collect::<Vec<_>>();
        accounts.sort();
        assert_eq!(accounts, vec!["nt_qq_aaaaaaaa", "nt_qq_bbbbbbbb"]);
    }

    #[test]
    fn pic_temp_dirs_collects_only_temp_subdirs() {
        let tmp = TempDir::new().unwrap();
        let acc = tmp.path();
        for month in &["2024-06", "2025-01"] {
            for sub in &["Ori", "Thumb", "OriTemp", "ThumbTemp"] {
                fs::create_dir_all(acc.join("nt_data/Pic").join(month).join(sub)).unwrap();
            }
        }

        let collected = pic_temp_dirs(acc);
        assert_eq!(collected.len(), 4); // 2 months × 2 temp subdirs
        for p in &collected {
            let name = p.file_name().unwrap().to_string_lossy().into_owned();
            assert!(
                name == "OriTemp" || name == "ThumbTemp",
                "unexpected dir picked up: {name}"
            );
        }
    }

    #[test]
    fn cache_actions_never_target_chat_history_or_login_state() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());

        let actions = collect_cache_actions(tmp.path());
        let paths = collect_paths(&actions);
        assert!(!paths.is_empty(), "tree should yield some cache actions");
        assert_forbidden_absent(&paths);
    }

    #[test]
    fn media_actions_never_target_chat_history_or_login_state() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());

        let actions = collect_media_actions(tmp.path());
        let paths = collect_paths(&actions);
        assert!(!paths.is_empty(), "tree should yield some media actions");
        assert_forbidden_absent(&paths);
    }

    #[test]
    fn cache_actions_use_direct_deletion() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());
        let actions = collect_cache_actions(tmp.path());
        for a in &actions {
            let CleanAction::Delete { via, .. } = a else {
                panic!("expected Delete");
            };
            assert_eq!(*via, DeletionVia::Direct);
        }
    }

    #[test]
    fn media_actions_use_trash_deletion() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());
        let actions = collect_media_actions(tmp.path());
        for a in &actions {
            let CleanAction::Delete { via, .. } = a else {
                panic!("expected Delete");
            };
            assert_eq!(*via, DeletionVia::Trash);
        }
    }

    #[test]
    fn cache_picks_expected_top_level_dirs_per_account() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());
        let paths = collect_paths(&collect_cache_actions(tmp.path()));

        // A few representative checks: each top-level cache dir is present
        // for the root and per-account log + log-cache + nt_temp shows up
        // for both accounts.
        assert!(paths.iter().any(|p| p.ends_with("/Cache")));
        assert!(paths.iter().any(|p| p.ends_with("/Code Cache")));
        assert!(paths.iter().any(|p| p.ends_with("/dynamic_package")));
        assert!(paths.iter().any(|p| p.ends_with("/global/nt_data/search")));

        for account in &["nt_qq_aaaaaaaaaaaaaaaa", "nt_qq_bbbbbbbbbbbbbbbb"] {
            assert!(
                paths
                    .iter()
                    .any(|p| p.contains(account) && p.ends_with("/nt_data/log")),
                "missing nt_data/log for {account}"
            );
            assert!(
                paths
                    .iter()
                    .any(|p| p.contains(account) && p.ends_with("/nt_temp")),
                "missing nt_temp for {account}"
            );
        }
        // Pic temp dirs picked up
        assert!(paths.iter().any(|p| p.ends_with("/OriTemp")));
        assert!(paths.iter().any(|p| p.ends_with("/ThumbTemp")));
    }

    #[test]
    fn media_picks_full_pic_directory_not_temp_only() {
        let tmp = TempDir::new().unwrap();
        build_qq_tree(tmp.path());
        let paths = collect_paths(&collect_media_actions(tmp.path()));

        // The whole Pic/ tree is the unit of removal — not the per-month
        // subdirs. That keeps the action list compact and matches what the
        // user would expect from "delete cached pictures".
        for account in &["nt_qq_aaaaaaaaaaaaaaaa", "nt_qq_bbbbbbbbbbbbbbbb"] {
            assert!(
                paths
                    .iter()
                    .any(|p| p.contains(account) && p.ends_with("/nt_data/Pic")),
                "missing nt_data/Pic for {account}"
            );
            for media in &["Video", "Ptt", "File", "Emoji", "avatar"] {
                assert!(
                    paths
                        .iter()
                        .any(|p| p.contains(account) && p.ends_with(&format!("/nt_data/{media}"))),
                    "missing nt_data/{media} for {account}"
                );
            }
        }
        assert!(paths.iter().any(|p| p.ends_with("/global/nt_data/Emoji")));
    }

    #[test]
    fn missing_qq_root_yields_empty_action_list() {
        let tmp = TempDir::new().unwrap();
        // Empty tempdir, no QQ tree.
        assert!(collect_cache_actions(tmp.path()).is_empty());
        assert!(collect_media_actions(tmp.path()).is_empty());
    }
}
